---
- name: User management
  hosts: demo
  become: true
  tasks:
    - name: Preconfig block
      become: true
      block:
        - name: Sleep
          ansible.builtin.command: /bin/sleep 15
          async: 1000
          poll: 5
          register: sleep
          changed_when: false

        - name: Show sleep result
          ansible.builtin.debug:
            var: sleep

        - name: Echo done
          ansible.builtin.command: echo "DONE"
          changed_when: false

    - name: Check sleep status
      ansible.builtin.async_status:
        jid: "{{ sleep.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 100
      delay: 1
      ignore_errors: true

    - name: Reboot
      ansible.builtin.reboot:
        reboot_timeout: 300
        pre_reboot_delay: 5
        post_reboot_delay: 30
        connect_timeout: 60
      become: true
