---
- name: "[{{ name }}] Создаем секрет"
  vars:
    envFile: "{{ lookup('file', role_path ~ '/services/' ~ name ~ '/.env') }}"
  community.docker.docker_secret:
    name: "{{ name }}.env"
    data: "{{ envFile | b64encode }}"
    labels:
      secrets: "{{ envFile | hash('sha1') }}"
    data_is_b64: true
    state: present