Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "weather-vm"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "forwarded_port", guest: 30080, host: 30080  # приложение
  config.vm.network "forwarded_port", guest: 30090, host: 30090  # prometheus
  config.vm.network "forwarded_port", guest: 30030, host: 30030  # grafana

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end
end