apiVersion: v1
kind: Service
metadata:
  name: weather-app-svc
  namespace: weather-monitor
spec:
  type: NodePort
  selector: { app: weather-app }
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
