apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: weather-monitor
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'weather-app'
        static_configs:
          - targets: ['weather-app-svc:8000']
